image:
  repository: xuanhoa2772004/vdt-api
  tag: "$TAG_NAME"
  pullPolicy: IfNotPresent


replicaCount: 1


service:
  type: NodePort
  port: 8000
  targetPort: 8000
  nodePort: 30004


resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi


env:
  - name: FRONTEND_ORIGIN
    value: "*"
  - name: MYSQL_HOST
    value: "mysql"  
  - name: MYSQL_PORT
    value: "3306"
  - name: MYSQL_DATABASE
    value: "vdt2025"  
  - name: MYSQL_USERNAME
    value: "root"  


mysql:
  host: "mysql"
  port: "3306"
  database: "vdt2025"
  username: "root"
  password: "hoa0976271476"  

labels:
  app: vdt-api
  version: v1 
